### ISSUE TITLE
Monitor the dev services

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#103]
Split from https://github.com/UserOfficeProject/stfc-user-office-project/issues/70. Requires #60 

We should monitor the dev and prod services. We might be able to use UserOfficeProject/user-office-backend#81, along with Heartbeat (see isisbusapps/fba-elastic-stack#42) or Jenkins if Heartbeat isn't available.

See [`Prod_Test.Ping_MailChimpWebhooks`](https://ci.devs.facilities.rl.ac.uk/view/MailChimpWebhooks/job/Prod_Test.Ping_MailChimpWebhooks/) for a similar job.

/overwrite opened 2020-09-04

**Comment by TeraMike** [comment]
Here are the monitoring jobs I have created. They ping the frontend and backend respectively every 15 minutes, and if they cannot reach it they will send a default content email on the first failure (and on fixed).  
[Frontend job](https://ci.devs.facilities.rl.ac.uk/job/Dev_Test.Ping_ProposalFrontend/) | [Backend job](https://ci.devs.facilities.rl.ac.uk/view/ProposalSubmission/job/Dev_Test.Ping_ProposalBackend/)

The frontend job is directed at `https://devproposal.facilities.rl.ac.uk`, and the backend at  `https://devproposal.facilities.rl.ac.uk/graphq`. It was suggested that the backend may want `/health` at the end but not sure if this is working.

If there is else these jobs can or should be doing please let me know, I am not too familiar with Jenkins :)

**Comment by TickleThePanda** [comment]
Just to double check, should it be `graphq` or `graphql` for the backend endpoint?

**Comment by TeraMike** [comment]
> Just to double check, should it be `graphq` or `graphql` for the backend endpoint?

Cosimo gave me graphq as the link but I wasn't sure myself. `graphql` would certainly make more sense but they both direct to the same place (503 error) so I haven't been able to check.

**Comment by TickleThePanda** [comment]
You should be able to test the jobs now against the dev environment.

I've just reviewed these a bit further and it looks like the current tests are following a test pattern for a JSON web service.

I think a better approach could be to take would be to use `Invoke-WebRequest` (it should work if we specify restrict the job to run on nodes with the tag `powershell-5`). Once you've made that request then to look at the returned status code (in other words, is it status 200?) or fail on a caught exception.

**Comment by TickleThePanda** [comment]
For the GraphQL endpoint, I'd expect that you'll have to make a more complex request to the GraphQL interface to get it to work. A post with the body content `{ "query": " query { _service { sdl } }" }` would work, I think.

**Comment by TeraMike** [comment]
> I think a better approach could be to take would be to use `Invoke-WebRequest` (it should work if we specify restrict the job to run on nodes with the tag `powershell-5`). Once you've made that request then to look at the returned status code (in other words, is it status 200?) or fail on a caught exception.

Out of curiosity, why is it that they need to run only on nodes with the powershell 5 tag (which would only be `fba-agent-6` if I'm not mistaken)? I'm not quite sure how to configure that setting so I just let it go and it does seem like they're working even on `fba-agent-1` which has powershell 4 as a tag.

**Comment by mr-field** [comment]
> Out of curiosity, why is it that they need to run only on nodes with the powershell 5 tag (which would only be fba-agent-6 if I'm not mistaken)?

They should work fine on Powershell 4 too, but the agent does need to have Powershell installed or the jobs will fail. Jenkins doesn't check this automatically, so we need to specify a label that restricts jobs to agents with the right software. However, I think all nodes have Powershell installed at the moment (even the Linux one) so we may not need any labels.

> It was suggested that the backend may want /health at the end but not sure if this is working.

The `/health` and `/readiness` backend endpoints are working, but they're not available outside the Kubernetes cluster. We should add [liveness and readiness checks](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) to the [Kubernetes config](https://github.com/isisbusapps/docker-orchestration/tree/develop/kubernetes/proposal-system) to let Kubernetes monitor the services status and restart them if they're down.

I know that the ESS are using these as their liveness and readiness endpoints:
- Backend
   - Liveness: `/health`
   - Readiness: `/readiness`
- Frontend
   - Liveness: `/`
   - Readiness: `/`
- Factory (only avaliable within the cluster network, not reachable by Jenkins)
   - Liveness: `/health-check`
   - Readiness: `/health-check`

**Comment by TickleThePanda** [comment]
> > Out of curiosity, why is it that they need to run only on nodes with the powershell 5 tag (which would only be fba-agent-6 if I'm not mistaken)?
>
> They should work fine on Powershell 4 too, but the agent does need to have Powershell installed or the jobs will fail.

I missed that Microsoft had split their documentation for newer and older Powershell so it looks like `Invoke-WebRequest` will work.

**Comment by TickleThePanda** [comment]
Just checked the jobs and these look good.

I think it will be worth having some extra information where the request fails - perhaps status code, status message, and body content.

**Comment by mr-field** [comment]
@TickleThePanda Any objections to calling this done? If the're OK, we should move to creating the prod version (https://github.com/UserOfficeProject/stfc-user-office-project/issues/104).

**Comment by TickleThePanda** [comment]
Looks good to me

**Comment by TeraMike** [comment]
Closing this then and moving to look at 104.
