### ISSUE TITLE
Frontend SDK generation has a dependency on the ESS Scheduler

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/stfc-user-office-project#105]
When generating the frontend SDK, there is a new dependency on the ESS Scheduler. This was added to our compose as a short-term solution (see https://github.com/isisbusapps/docker-orchestration/pull/72), but in the longer term this isn't ideal as we don't use the Scheduler and don't want to have to support it.

**Comment by TickleThePanda** [comment]
I believe this isn't an issue anymore.
