### ISSUE TITLE
Add tests for Editable Submitted Proposal

### ISSUE THREAD

**Issue by Ziggiyzoo** [UserOfficeProject/stfc-user-office-project#108]
The new ability to edit proposals after submissions requires tests to be added, tests for:

-Is the proposal editable after submissions
-Do the edited changes save

These are just specifically assigned to the proposal itself. However I am not sure how the changes to the proposal workflow will affect anything further along, as the proposal is still editable, but keeps `submitted = true` which may cause issues when editing.

**Comment by TickleThePanda** [comment]
Blocked by #88

**Comment by TickleThePanda** [comment]
Tests should now be runnable in local environments.

**Comment by simonfernandes** [comment]
Completed as part of https://github.com/UserOfficeProject/user-office-frontend/pull/403
