### ISSUE TITLE
Improve reference number format user experience

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/stfc-user-office-project#110]
When adding a reference number format to a call, there is no information displayed on how the format should be formatted. There is also no validation to stop the user officer from inputting an invalid format. 

We should add some information (tooltip?) and validation to make it easier for user officers to use.

**Comment by RasmiaKulan** [comment]
### Current Implementation
The `CallGeneralInfo.tsx` uses Formik `< /Field>` for the implementation of `Update the call` form.
Formik Field uses inbuilt features like `KeyboardDatePicker` which displays the picker along with the text field and there isn't any such thing to display a text field with help/information icon. I have been trying to find a hack around it and have come up with the following suggestions:

![Errormessage](https://user-images.githubusercontent.com/69144386/123788191-a1d93d80-d8d3-11eb-821e-dcd176bc33f4.PNG)
![Tooltip error](https://user-images.githubusercontent.com/69144386/123788195-a43b9780-d8d3-11eb-80d6-b411bd8de47f.PNG)
 I am keener on the first one as the help icon in the second one appears in an odd position and I couldn't find a way to place it in line with the text field.

**Comment by JEThompson97** [comment]
It is a shame we can't get the '❔' to appear in-line, like the date-picker..

My vote would be for the **first option** 🙂

I wonder if we should replace the word '_alphanumeric_' with '_letters and/or numbers_' for clarity?
But then again, when you google alphanumeric it gives a very clear definition, so not sure if that change is necessary.

**Comment by martin-trajanovski** [comment]
> ### Current Implementation
> The `CallGeneralInfo.tsx` uses Formik `< /Field>` for the implementation of `Update the call` form.
> Formik Field uses inbuilt features like `KeyboardDatePicker` which displays the picker along with the text field and there isn't any such thing to display a text field with help/information icon. I have been trying to find a hack around it and have come up with the following suggestions:
> 
> ![Errormessage](https://user-images.githubusercontent.com/69144386/123788191-a1d93d80-d8d3-11eb-821e-dcd176bc33f4.PNG)
> ![Tooltip error](https://user-images.githubusercontent.com/69144386/123788195-a43b9780-d8d3-11eb-80d6-b411bd8de47f.PNG)
> I am keener on the first one as the help icon in the second one appears in an odd position and I couldn't find a way to place it in line with the text field.

Hi Rasmia,

I still think it is doable and you can try using something like this: 
`InputProps={{
     endAdornment: <InputAdornment position="end">Kg</InputAdornment>,
 }}`
on the field itself directly.
Here is some useful information as well https://material-ui.com/components/text-fields/#input-adornments

**Comment by RasmiaKulan** [comment]
> Hi Rasmia,
> I still think it is doable and you can try using something like this:
> `InputProps={{ endAdornment: <InputAdornment position="end">Kg</InputAdornment>, }}`
> on the field itself directly. So instead of Kg here in the example you can use some icon, tooltip or whatever you need.
> Here is some useful information as well https://material-ui.com/components/text-fields/#input-adornments
Great! I will look into it @martin-trajanovski. Thank you 🙂

**Comment by RasmiaKulan** [comment]
### **Updated**
I have now made a few more changes. Feedback on how it looks and if something needs to be changed would be appreciated😊
### **Detecting invalid input**

![validation](https://user-images.githubusercontent.com/69144386/124145979-359e3b80-da85-11eb-9d35-1d39821be7dc.gif)

### **Assisting Users**

![assisting](https://user-images.githubusercontent.com/69144386/124145927-27e8b600-da85-11eb-9b73-d35a2b8806b5.gif)

**Comment by TCMeldrum** [comment]
Looks good, would it be worth giving an indication of how long the suffix and prefix can be? 

Also, how does the reference number format work? Will the middle always have the "{digits:" if so worth splitting it into 2 textboxes one for XXX and one for YYY and combine the inputs later?

**Comment by simonfernandes** [comment]
It looks good, the modal is a great idea I think! 😀 Some suggestions: 

- Instead of "invalid suffix", I think "invalid parameter" would be better. We should probably avoid saying prefix, for consistency and because there could (eventually) be multiple parameters
- Black would be a better text colour for the modal so that it doesn't look like too much like an error and is easier to read.
- Might be nice if there's a way to get `code snippet` formatting into that modal somehow, to make the examples easier on the eye
- I think the modal text might need to be simplified somehow. I know that we're regulating this with policy rather than validation, but the ESS might use this feature and it'd still be good to have some good documentation for it for developers and users alike. It's not the easiest thing to explain clearly but I think one thing we should do is add some valid examples. I've had a go below:

----
A reference number format determines how reference numbers are generated for submitted proposals. It consists of a **prefix** and **digits parameter**.

The **prefix** can contain alphanumeric characters and is what all generated reference numbers will begin with. For example, `21a`.

The **digits parameter** is a numerical value that determines how many digits a proposal's sequence number is, including padding. It is written as `{digits:x}`, where x is a number. For example, if the value of the parameter is 6 (`{digits:6}`), the first proposal will be numbered 000001, the second 000002, and so on.

### Valid examples
| Format | Generated reference numbers | 
--------|---|
abc{digits:3} | abc001, abc002, abc003
211{digits:5} | 21100001, 21100002, 21100003

**Comment by martin-trajanovski** [comment]
@RasmiaKulan I think it is not a good practice to use modal over another modal because we already have one modal opened for editing call. And I also think that it is too much to click twice to open and close just to see the message. I guess it is better to use just a normal tooltip with an icon without a button. Something like this: 
`<Tooltip
            title={`Reviewed by ${proposal.technicalReview?.reviewer?.firstname} ${proposal.technicalReview?.reviewer?.lastname}`}
          >
            <InfoIcon fontSize="small" />
          </Tooltip>`
In the tooltip message you can write the message for the format and with just hovering over that icon it will show it. Not really sure but for me this is much better solution then clicking twice just to see information message.

**Comment by RasmiaKulan** [comment]
@martin-trajanovski That does make sense but the reason we decided to use a modal was that the explanation on what the right format should be is quite extensive (as mentioned above by Simon) and fitting it all in a tooltip didn't look appealing.

**Comment by martin-trajanovski** [comment]
> @martin-trajanovski That does make sense but the reason we decided to use a modal was that the explanation on what the right format should be is quite extensive (as mentioned above by Simon) and fitting it all in a tooltip didn't look appealing.

Then it is fine by me if you already agreed on that 👍

**Comment by JEThompson97** [comment]
> Also, how does the reference number format work? Will the middle always have the "{digits:" if so worth splitting it into 2 textboxes one for XXX and one for YYY and combine the inputs later?

I think this is a nice idea! Splitting the entry into 'Reference Number Prefix Format' and 'Reference Number Digits'. It'd make it simpler for the user, and allow us to break down the validation.

Not sure if there was a reason we originally wanted the user to enter the `XXX{digits:YYY}` format? Was this part of the requirements or something @TickleThePanda ?

**Comment by TickleThePanda** [comment]
The reason for why we didn't have 2 boxes for this is that it ties the reference number to our format (prefix and incrementing suffix) rather than a general flexible format.

If we were happy with splitting it, I wouldn't mind that.

**Comment by RasmiaKulan** [comment]
### Further Updates
Splitting the entry does make it simpler for the user but it makes the system less flexible to different reference number formats in the future. I have made the following change to the modal with what @simonfernandes suggested. Feedback on how it looks and if something needs to be changed further would be appreciated 😊

![updated-modal](https://user-images.githubusercontent.com/69144386/124760519-bc8d6100-df28-11eb-9254-11be75ad834f.gif)

**Comment by JEThompson97** [comment]
I'd say the design looks good and that this is ready for a PR 🙂
