### ISSUE TITLE
Run tests on GitHub actions

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/stfc-user-office-project#121]
Run the e2e tests on windows docker containers within github actions.

**Comment by TickleThePanda** [comment]
Blocked by #120 and #119

**Comment by TCMeldrum** [comment]
I have been looking into what needs to be done for this:

- Create dockercompose.e2e files for each service needed
- Work out how we pull in sensitive data like issue: https://github.com/UserOfficeProject/stfc-user-office-project/issues/55
- Create a cypress docker image:
   * Cypress support official Linux images but not windows ones
   * Cypress may depend on DirectX dll files not on the windows servercore image
   * Full windows image may contain the needed files however but is large and we currently don't support it. 
   * Info found a thread on github: https://github.com/cypress-io/cypress-docker-images/issues/261

**Comment by TickleThePanda** [comment]
Blocked waiting for results from Docker project status.

**Comment by TickleThePanda** [comment]
I don't think we need to do this anymore.
