### ISSUE TITLE
LSF users will be able to see the core data of their legacy proposals

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#122]
This should be:
 - Reference number
 - Title
 - Abstract
 - Experimenters

**Comment by WhittyPM** [comment]
Following LSF meeting. Andy would requested that objectives be add to the core data (in addition to the above) that can be extracted for initial rollout @TickleThePanda @EdwardHaynes 
Is this at all possible?
