### ISSUE TITLE
Make sure that the application is GDPR compliant

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#13]
Make sure that the application is GDPR compliant.

This should involve a team activity for identifying and discussing the issues around how users interact with the ESS software. It should only cover the areas that our users will interact with in the new system. We should open the issues identified as new issues.

Impacted users: All

Project requirement: [proposal-91](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=91)

**Comment by TickleThePanda** [comment]
This should only include reviewing the GDPR aspects of:
 - proposal submission
 - proposal review

We should ensure that other parts of the application are disabled as part of #54

**Comment by TCMeldrum** [comment]
Split into #146 #147 #148 #149 #150
