### ISSUE TITLE
As a submitter I can attach my DOI making it easier for me to access my publications

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#134]
Requested by Greg Greetham - CLF (LSF)

can they attach "associated publications" in a sensible way? DOI? making it easy for the reviewers to access the publications? PDF? 

Panda confirmed this would be a planned improvement    (SP requirement list #95)

**Comment by TickleThePanda** [comment]
Duplicate of #31

**Comment by WhittyPM** [comment]
Thanks @TickleThePanda
