### ISSUE TITLE
Calls can be created without a call template

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/stfc-user-office-project#140]
When you create a call, it can be created without selecting a call template (pictured). Then, when you try to submit a proposal to the call it fails because it's missing.

There should be some validation on the field that makes it required. If there is only one call template available, maybe it should also be pre-selected.

![calltemplate](https://user-images.githubusercontent.com/14293717/121518961-0007b480-c9e9-11eb-8d18-66e389473324.png)

**Comment by JEThompson97** [comment]
Looks like this is resolved be https://github.com/UserOfficeProject/user-office-backend/pull/357
Shall we close this one?

**Comment by simonfernandes** [comment]
Resolved via https://github.com/UserOfficeProject/user-office-backend/pull/357
