### ISSUE TITLE
Trigger deployment to our development environment on latest image updated

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#142]
We need some way to trigger our deployment pipeline for our development environment when our GitHub actions have finished.

The solution to this is likely https://github.com/isisbusapps/ISISBusApps/issues/390 with webhook triggers.

**Comment by TickleThePanda** [comment]
We could either do this with hooks from GitHub actions or through DockerHub.

**Comment by TickleThePanda** [comment]
Blocked by isisbusapps/ISISBusApps#390

**Comment by TickleThePanda** [comment]
No longer blocked.

**Comment by TickleThePanda** [comment]
We should now be able to trigger Jenkins from the outside world with the changes made isisbusapps/ISISBusApps#390.

This will need new "rollout" Jenkins jobs that trigger the kubernetes rollout of the correct image and runs the database patches.

**Comment by mr-field** [comment]
The proposals deployments [are configured](https://github.com/isisbusapps/docker-orchestration/blob/c99ccd0a2c504c2f549c9fa69cca34f95040868a/kubernetes/proposal-system/proposal-backend/base/deployment.yaml#L18) to pull the latest image on restart, so the Jenkins job needs only one command to apply the latest changes: `kubectl rollout restart deploy/<deployment name>`. Not sure how the DB patches work tough.
