### ISSUE TITLE
Deploy to prod linux environment

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#145]
What we need to do here:
 - [x] Provision prod cluster on SCD cloud using Magnum. This should match the current dev cluster setup:
    - Template: `kube-1.16.13-with-isis-dns`
    - Master Count: 1
    - Node Count: 1
    - Docker Volume Size (GB): 3GB
    - Keypair (?)
    - Master flavour: `c2.small`
    - Node flavour: `c2.small`
 - [x] Get cluster URL and credentials for cluster setup and deployment - use the `openstack` CLI
 - [x] Add credentials to Jenkins as a secret
 - [x] Extend [config](https://github.com/isisbusapps/docker-orchestration/tree/develop/kubernetes) for cluster setup (if required)
 - [x] [Set up cluster](https://github.com/isisbusapps/docker-orchestration/tree/develop/kubernetes/cluster-setup) with new prod Jenkinsfile
 - [x] Get DI to make network changes (from prod web proxies to cluster ingress and give nice DNS)
 - [x] Extend [config](https://github.com/isisbusapps/docker-orchestration/tree/develop/kubernetes) for prod versions
 - [x] Add prod version of Jenkins jobs to deploy proposals to cluster (using develop branch for testing)
 - [x] Merge config (docker_orchestration and BisAppSettings) into master 
 - [x] Make sure all Jenkins jobs to use master instead of develop

**Comment by RasmiaKulan** [comment]
This should also include moving sensitive data related to prod database into an external config.
Check `Actions Required` in https://github.com/UserOfficeProject/user-office-backend/pull/291

**Comment by ACLay** [comment]
Requires #144

**Comment by TickleThePanda** [comment]
We want to get to the point where we have an IP address for the ingress to make sure that we have the network requests into DI as soon as possible.

**Comment by TCMeldrum** [comment]
Made the following request to DI:

-         Make the domain name kubernetes.devs.facilities.rl.ac.uk point at 130.246.213.94 
-         Allow FbaProxExWeb.isis.cclrc.ac.uk (130.246.92.78) to connect to 130.246.213.94:443 
-         Make the domain name proposal.facilities.rl.ac.uk point to FbaProxExWeb.isis.cclrc.ac.uk (130.246.92.78) 
-         proposal.facilities.rl.ac.uk will be what users connect to so must be available from outside the STFC network 
Ticket: INC-110752

**Comment by TickleThePanda** [comment]
I've asked Alan to prioritise this ticket.

**Comment by TCMeldrum** [comment]
DI have said they have made the changes

**Comment by TCMeldrum** [comment]
Emailed database service about permission issue

**Comment by TCMeldrum** [comment]
Ticket to access proposal.facilities.rl.ac.uk outside VPN: INC-111728

**Comment by TCMeldrum** [comment]
I believe prod is fully up and running hopefully I have not missed anything. I wrote up [some instructions](https://github.com/isisbusapps/ISISBusApps/wiki/Creating-Kubernetes-cluster-for-the-proposal-system) for if we ever need to replicate this if anyone wants to fact check them.
