### ISSUE TITLE
Review how data is used in the relevant areas of the application for GDPR

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/stfc-user-office-project#150]
split from #13 

This issue just relates to the review of the parts of the application that the stfc uses for any GDPR issues. Identified issues are written up and added to the project board.

**Comment by TCMeldrum** [comment]
Identifyed issues: #146 #147 #148 #149

**Comment by TickleThePanda** [comment]
Closed by #146 #147 #148 #149 opened
