### ISSUE TITLE
Cannot submit proposal on behalf of another user

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/stfc-user-office-project#152]
User isn't always one of the principal investigator or co-proposers (could be an assistant) however the system block you from submitting a proposal if you are not part of it.

**Comment by TickleThePanda** [comment]
Waiting on #146

**Comment by TickleThePanda** [comment]
This needs investigating to see if it is a bug or whether the user experience could be improved.

A user who is creating a proposal should automatically be added as a CoI if they change the PI to somebody other than themselves.

**Comment by TCMeldrum** [comment]
To elaborate on this issue, we still need users to be part of the proposal so if they are the co-proposer however they are not automatically added as a co-proposer when removed as the principal investigator. So we want when the user is removed as the principle investigator to be automatically added as a co-proposer. We could also add that they cannot be removed as a co-proposer as well.
