### ISSUE TITLE
Require SSL when connecting to DB

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/stfc-user-office-project#155]
Now that we turned on SSL on our Postgres DB (#93), we should change the dev connection string in BisAppSettings to set the SSL mode as "Required". Without this, the dev backend thows this error when starting up, possibly beacuse it's looking for client certificates:
```
no pg_hba.conf entry for host <database IP address>, user \"ess_test\", database \"ess_test\", SSL off
```

**Comment by mr-field** [comment]
See the `UserOfficeProject/stfc-user-office-project#155_require_ssl` BisAppSettings branch for the fix.

**Comment by ACLay** [comment]
Looks fine to me 👍

**Comment by simonfernandes** [comment]
👍

**Comment by mr-field** [comment]
The branch has now been merged into `develop`.

This particular error has been solved, but the backend still won't start because of #154.
