### ISSUE TITLE
Integrate with LSF scheduling

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#169]
Part of #11

This will require the correct data to be available in SharePoint to be updated in the proposal list cache.

The proposal lookup service should be updated to support getting data from the new proposal software.

**Comment by TickleThePanda** [comment]
The main work that we need to do here is to listen to the events that happen on the message queue. We can then listen to these events from the allocations service.

**Comment by TickleThePanda** [comment]
There's two parts of this:
 - Getting the data so we can allocate time to it (we need to do this)
 - Getting the scheduler to read information about proposals from the new proposal software (which is being done by the schedule team)

**Comment by TCMeldrum** [comment]
Notes for design review:

The overview is that we need to get data out of the database using proposal allocations. Proposals Allocations will subscribe to events from the backend then and fetch the relevant data based on the event. 

An overview of what the backend currently sends to the message queue:
Backend sends messages on the following events:
- PROPOSAL_STATUS_CHANGED_BY_USER 
- PROPOSAL_STATUS_CHANGED_BY_WORKFLOW

These send to the SCHEDULING_PROPOSAL and PROPOSAL queues (but only if the proposal has the ProposalStatusDefaultShortCodes.SCHEDULING sort code)

- PROPOSAL_CREATED
- PROPOSAL_UPDATED
- PROPOSAL_MANAGEMENT_DECISION_SUBMITTED
- TOPIC_ANSWERED

These send events to the `useroffice.fanout` exchange

And listens for events on the SCHEDULED_EVENTS queue for the following events:
- PROPOSAL_BOOKING_TIME_REOPENED
- PROPOSAL_BOOKING_TIME_UPDATED
- PROPOSAL_BOOKING_TIME_ACTIVATED
- PROPOSAL_BOOKING_TIME_SLOTS_REMOVED
- PROPOSAL_BOOKING_TIME_SLOT_ADDED

A few questions for discussion:
- What do we need to be sent over the message queue?
- If SFTC and ESS want different events over the queues how do we deal with this? 
- Are there any other apps that we should future proof for?

**Comment by TCMeldrum** [comment]
Design Review outcome:

Events we need for proposal allocations:
PROPOSAL_SUBMITTED -> we can caught this within PROPOSAL_STATUS_CHANGED_BY_WORKFLOW
PROPOSAL_UPDATED
PROPOSAL_DELETED / EXPIRED

Event filtering will happen at application layer so us and ESS can share a message brooker. 

Create a wiki page with events/queues and our customers on confluace.

**Comment by TCMeldrum** [comment]
Split into:

- https://github.com/UserOfficeProject/stfc-user-office-project/issues/328
- https://github.com/UserOfficeProject/stfc-user-office-project/issues/329
- https://github.com/isisbusapps/proposal-allocations/issues/171

**Comment by TickleThePanda** [comment]
On the scheduler side there's also https://github.com/isisbusapps/Schedule/issues/3395
