### ISSUE TITLE
Chaos testing 

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#196]
In a previous project planning meeting Fredrik (ESS) reported that their team have a fairly stable environment but feels that they need more documentation. Specifically around recovering from issues. One example of this was the ESS had faced an issue, but in attempts to fix it in Kubernetes (IT people had messed up proxy) the team had messed up their own cluster and took some time to recover. 

Fredrik reported that the issues they faced were: 
•	Outside proxy was changed. Had to do special curl commands (circumvent the DMS)
•	If you mess up the ingress on one deployment you can take down other parts on the cube cluster
•	Nodes running out of memory

Fredrik reported that before his team releases a new version they take production DB and put it on developer test (due diligent). 

  P&O team have roll back scripts but in certain circumstances there is a chance that data could be lost. Also unsure how easy this is but ideally everything should have a rollback. 

**_This could be a potential issue for P&O and is worth exploring ways to reduce the risk by undertaking Chaos testing_**

**Comment by mr-field** [comment]
I've come up with a few ways of breaking the proposal apps. I've scheduled an exercise session between 15/11/21 and 18/11/21, when I'll cause the system to break while the rest of the team tries to fix it. This should prepare us for when real problems happen and highlight any processes or problems that can be improved.

**Comment by mr-field** [comment]
Before the session starting on the 15th, https://github.com/isisbusapps/docker-orchestration/issues/184 needs to be completed so that developers know what to do.

**Comment by mr-field** [comment]
The chos testing is now over and we've had a debriefing meeting to go over the experience. I've detailed the whole exercise on the [Proposal crisis silmuations](https://github.com/isisbusapps/ISISBusApps/wiki/Proposal-crisis-simulations) page on the wiki, including what happened and what we thought of the exercise afterwards.

These are the possible actions highlighted in the [restrospective](https://github.com/isisbusapps/ISISBusApps/wiki/Proposal-crisis-simulations#Restrospective) and follow-up meetings:
- Add more details to [the wiki](https://github.com/isisbusapps/ISISBusApps/wiki/Our-Kubernetes-clusters#Internal-cluster-services) for cluster services
- Split off the proposals deployments into a new repo, leaving only internal services in `docker-orchestration`. This might make finding internal services easier
- Automate monitoring of internal cluster services, for example with a Jenkins job. Checking the running services against a known list would also document which services we expect to be running
- Add a high-level overview of how the reverse proxies work to the wiki
- Send proxy logs to Elatic and document how to find them
- Add a description to Jenkins jobs, maybe with links pointing to relevant wiki pages
- Add two wrappers around `kubectl` to our Linux setup for connecting to the dev or prod cluster
- Make more P&O prod monitoring jobs send alerts to the main proposal channel
