### ISSUE TITLE
Change favicon to be configured to orginsation

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/stfc-user-office-project#197]
The favicon is currently set to the ESS logo, we want this to be able to a be to the STFC logo when it is launched in STFC mode but stay the same for ESS mode. This could be a candidate for placing the logo in the settings table.

**Comment by AspectVI** [comment]
Created a Plan for what seems to be needed for this but still lacking core understanding to implement a working solution.

Changes:
- favicon.ico to faviconESS.ico
- frontend - public - index.html:
	<link rel="shortcut icon" href="%PUBLIC_URL%/faviconESS.ico?v=1" />
- Add faviconSTFC.ico to users-office-frontend/Public
- user-office-backend/src/sftc:
	Add something here for triggering the favicon 
- user-office-backend/src/sftc:
	Add somthing here for triggering the old favicon
- possibly add <link rel="shortcut icon" href="%PUBLIC_URL%/faviconSTFC.ico?v=1" /> to public/index.html or somewhere but not sure

It seems like I will need to create a second version of "frontend - public - index.html" for stfc and then add to the config folders "user-office-backend/src/sftc" and "user-office-backend/src/ess" to get them to launch their correct version. 

That last bit I am not sure how to do so will look for advice.

**Comment by AspectVI** [comment]
Have done the following si far:
- renamed favicon.ico to faviconESS.ico
- renamed public/index.html to public/indexESS.html
- added public/indexSTFC.html
- - updated other Favicon references that seemed to need changing to reference faviconESS for now.
