### ISSUE TITLE
Add performance metrics to endpoints

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#199]
As we may expect performance issues in production, we should add performance metrics to endpoints.

At a minimum this should be just for the whole of graphql but it should ideally be split by type of query.. 

We should make sure that the formatting of this is able to be processed by logstash.

**Comment by ACLay** [comment]
With the changes and secrets now deployed to dev, we're seeing the following error messages being logged:
```
Error sending report to Apollo servers: service:<service name>:<key>
 is not a legal HTTP header value
```
It looks like the problem might be that there's a newline at the end of the secret file, which is being included in the secret (as well as the log message), and [newlines are invalid in HTTP headers](https://stackoverflow.com/a/47422593/16235117)

I've a BisAppSettings branch to remove the newlines: `stfc-user-office-project#199_header_whitespace`

**Comment by TCMeldrum** [comment]
stfc-user-office-project#199_header_whitespace looks good 👍

**Comment by ACLay** [comment]
Bisapps changes merged following this review and one from @TickleThePanda on teams

**Comment by ACLay** [comment]
Shoot. I thought I was just deleting an old local testing variant of the graph from apollo studio. Turns out I deleted the whole graph, including the dev config. So now we need to remake the graph and update the connection values.

BisAppSettings changes are on `stfc-user-office-project#199_new_graph_id`

**Comment by TickleThePanda** [comment]
LGTM

**Comment by TCMeldrum** [comment]
👍

**Comment by ACLay** [comment]
Okay, usage reports seem to be being sent up to studio now. Last step for dev will be setting up daily reports: https://www.apollographql.com/docs/studio/daily-reports/

This requires setting up a channel and webhook in slack. @TickleThePanda should we ask the ESS about setting this up in the current slack workspace? Or should we look at setting up a new one (or reviving the old BisApps workspace)?

**Comment by ACLay** [comment]
@TickleThePanda any preferences on where to send the slack reports?

**Comment by TickleThePanda** [comment]
I don't think we should set up a slack workspace just for reports (I think it's as unlikely to be seen as just looking at the performance online). We could ask the ESS but I wouldn't want to force them to do it.

**Comment by ACLay** [comment]
I spoke with Fredrik last week to get a channel set up to receive the performance notifications. Apparently the ESS slack admins only set it up for him to have access. He messaged them last Thursday asking for more people to be added.

When checking slack earlier I noticed that our slack accounts are all set up as single channel guests, apart from Ellen, Mika and Vyshnavi, who are multi-channel guests (this is indicated by the shape of the accounts status indicator) https://slack.com/intl/en-gb/help/articles/202518103-Understand-guest-roles-in-Slack I suspect we'll need to get permissions changed for most of us at some point, but I'll give it a little longer to see if I hear anything back through Fredrik.

**Comment by ACLay** [comment]
@TickleThePanda @mr-field Fredrik's had our accounts upgraded to multi channel guests with access to the new `user-office-daily-reports` channel, and I've set up the notification link for dev.

It looks like it's working fine, so I'll start putting a prod config PR together.

**Comment by mr-field** [comment]
It's working fine for me, I can access the new channel.

**Comment by TickleThePanda** [comment]
I can see it.

**Comment by ACLay** [comment]
I've added the new `current` variant for the prod api through the web interface. I used the local introspection option, pointing at `https://devproposal.facilities.rl.ac.uk/graphql` since introspection didn't seem to work against prod, and they should be using the same schema (or close enough at least).

**Comment by ACLay** [comment]
Spend ages searching for the "Add notification" button. A hard refresh of the graph's settings page did the trick. We've now got slack notifications set up for both dev and prod. Assuming they both come in tomorrow morning I think we can consider this one closed.

**Comment by ACLay** [comment]
Reports are coming through as expected to the `user-office-daily-reports` channel on slack
