### ISSUE TITLE
Configure Factory to use STFC logo when in running in stfc mode

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/stfc-user-office-project#201]
Currently, the factory always uses the ESS logo when creating PDFs, we want a way to use the STFC one. The factory does not have a way of distinguishing which facility it is running in so might need to add this functionality or maybe it could use the logo from the database.

**Comment by TickleThePanda** [comment]
Rather than specifically change to use the STFC logo when running in STFC mode (which ties the logic of the software to our environment), I think the logo should be attached, in some way, to the factory - by a volume, for example (like we do with the base software.

**Comment by mr-field** [comment]
All required PRs have now been merged.
