### ISSUE TITLE
Attach user contributed document to end of generated proposal document

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#204]
We should attach proposal PDFs (like the science case) to the end of the generated PDF proposal document.

I'm not sure what happened to this requirement in the project.

**Comment by TickleThePanda** [comment]
I think we would be able to leave this until after the release but it would need to be done before the bulk of proposals are submitted.

**Comment by TickleThePanda** [comment]
We could possibly use something like [`pdf-lib`](https://github.com/Hopding/pdf-lib)

**Comment by mr-field** [comment]
Currently, files are attached at the end of the generated PDF as "appendices". They're not technically concatenated, so they show in a slighly different page format but still at the end of the document. The questions that asked for the document have an answer like `see appendix <document filename>`, and the PDF has an item in the attachment list of every attached document.

See [this PDF](https://github.com/UserOfficeProject/stfc-user-office-project/files/7225678/2021_Campo_043819.pdf) as an example.

**Comment by TickleThePanda** [comment]
I think that might be enough here. We are planning a review of the PDFs generated by the software before we release so we can see if this is good enough as it is.

**Comment by TickleThePanda** [comment]
Closing this for the above reason.
