### ISSUE TITLE
Security Audit/Threat Analysis of Proposal Web Apps

### ISSUE THREAD

**Issue by TeraMike** [UserOfficeProject/stfc-user-office-project#205]
Assessing potential data/security threats and vulnerabilities to and of the proposal apps.

Naturally-following documentation is risk assessment and mitigation plan.

**Comment by mr-field** [comment]
Thanks, looks good to me. I've opened 2 issues as follow-ups from this. I don't think they're too high-priority, but it's worth keeping them in mind:
- https://github.com/UserOfficeProject/stfc-user-office-project/issues/262
- https://github.com/UserOfficeProject/stfc-user-office-project/issues/263

I think the issue can be closed now, given that two people have had a look at the report.

**Comment by TeraMike** [comment]
Nice spot on opening those, thanks.

I'll close it now since two others have had a look at it and I don't think there's anything more pressing that it will bring up from here.
