### ISSUE TITLE
Fix database connection errors for factory

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#206]
This was identified from [a database connection error] that causes a failure when trying to download a proposal as a PDF with file attachments.

Similar problem to https://github.com/UserOfficeProject/stfc-user-office-project/issues/155 but in this case we [aren't able to use the database URL](https://github.com/UserOfficeProject/user-office-factory/blob/develop/src/dataSources/postgres/database.ts#L11) to configure this connection.

We should either:
1. Allow the database to be configured using a database URL (though we should maintain the existing functionality so that we don't break the ESS configuration)
2. Add an additional env to enable SSL

While we're at it, we should also ensure that we have disabled SSL checks like we did in https://github.com/isisbusapps/docker-orchestration/issues/144.

[a database connection error]: https://devlogs.devs.facilities.rl.ac.uk/app/discover#/doc/152a3fd0-cdb0-11ea-b964-d72e65fddf1f/kubernetes-bisappslogs-7.13.2-2021.09.22?id=z-2LDHwBmfPInhj3uK35

**Comment by mr-field** [comment]
This works on dev now after merging the 2 linked PRs.
