### ISSUE TITLE
Fix GDPR concerns where data is exposed over GraphQL

### ISSUE THREAD

**Issue by sc19ew** [UserOfficeProject/stfc-user-office-project#209]
Fixes from investigation in #148.

Reduce the permissions on the following user queries so they cannot be accessed when logged in as a USER or when not logged in at all:

- [x] getuser
- [x] getbasic

**Comment by sc19ew** [comment]
After discussion it seems the best way to go about changing the _getbasic_  query would be to alter the places that use _getbasic_ when logged in as a USER as if these points were not triggered by when logged in as a USER then the query could simply have its role in the authorized decorator changed. 

So far these points are when the details of either a PI or  a co-proposer needs to be displayed.

**Comment by sc19ew** [comment]
The changes necessary for _getuser_ are much simpler as this query is not triggered when logged in as a USER so the authorized tag can simply be updated to only allow access by a User Officer.

**Comment by sc19ew** [comment]
Proposed solution: 
Add USER_OFFICER and INSTRUMENT_SCIENTIST permissions only to getBasic, then to fix the issues that causes add a new query that only deals with adding/setting the PI to a proposal getBasicProposer, this query will not be limited to only USER_OFFICER and INSTRUMENT_SCIENTISTS but has a flag that states that it was called from either the resolver that sets the user as the PI or when generating the proposal PDF, therefore limiting the places this will be accessible to a regular USER.

**Comment by TickleThePanda** [comment]
How does the flag get set on the query?

**Comment by sc19ew** [comment]
From being called from either the resolver to set the PI or when generating the PDF

**Comment by TickleThePanda** [comment]
Sorry - what sets it, is it the person calling the method or is it in the backend?
