### ISSUE TITLE
Fix config file loading

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/stfc-user-office-project#216]
In #158 we changed the CONFIG_PATH environment variable from `/FBS/config/` to `/config/backend-config/local`

The new value has no trailing slash, and the code that combines this with NODE_ENV to get the full environment config path does a simple string concatenation. As a result, starting the backend results in the contents of the file not being read. `/config/backend-config/localdevelopment.env` doesn't exist, and should be  `/config/backend-config/local/development.env`.

The quick fix is to just add a trailing slash to CONFIG_PATH, but we should also aim to use a proper path handling library to make the path that can add slashes as required.

**Comment by IVlaD17** [comment]
Closed by https://github.com/isisbusapps/docker-orchestration/pull/161
