### ISSUE TITLE
Users searchable preferences aren't being respected

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/stfc-user-office-project#217]
If you deselect the "Please tick here to allow other users to add you to any proposals and visits. They will only be able to find you if they know your email address." in the Privacy Settings section of our ManageDetails page, your account can still be found in the Add Co-Proposers dialog.

It looks like none of the UOWS requests in [our datasource](https://github.com/UserOfficeProject/user-office-backend/blob/develop/src/datasources/stfc/StfcUserDataSource.ts) use the `getSearchableBasic(Person|People)Details...` methods which should be used and respect the preference.

The solution may not be as simple as just swapping those methods. We should consider what happens if a user is added to a proposal and later opts to not be searchable.

**Comment by TickleThePanda** [comment]
> It looks like none of the UOWS requests in our datasource use the getSearchableBasic(Person|People)Details... methods which should be used and respect the preference.

Good catch.

> The solution may not be as simple as just swapping those methods. We should consider what happens if a user is added to a proposal and later opts to not be searchable.

If the person is no longer searchable, they will continue to be on any proposals and visits they were on before and we will continue to show their details to the relevant people. It will only stop them from being searchable.

However, we need to consider how `getPreviousCollaborators` works to make sure that only returns searchable people.
