### ISSUE TITLE
Users stay logged in even if their credentials have been expired/invalidated

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/stfc-user-office-project#225]
If I log into the proposals system and then in a separate tab logout of the users/office site, the token that was used to authenticate me is invalid, but I'm still able to continue using the proposal site.

You could even logout, and use a separate computer to change your password. You'd still be authenticated and fine to proceed in the proposals system

I think we should be making more calls to the uows to check that the users credentials are still valid.

**Comment by TickleThePanda** [comment]
I think we could do this by checking the external token [`Authorized`](https://github.com/UserOfficeProject/user-office-backend/blob/5346d367f72b3a6fba701eb4ea250cbf881d2545/src/decorators/Authorized.ts#L8) and returning `NOT_LOGGED_IN` if the token has expired. If the token has expired, we trigger the login process.

**Comment by TCMeldrum** [comment]
Unless I miss understand I don't think that will work as the token cannot be passed to the authorized decorated as the token is not passed to the functions. Is there a way to get the token at this point in the code?

**Comment by TickleThePanda** [comment]
Could we add the external token to the [`UserWithRole`](https://github.com/UserOfficeProject/user-office-backend/blob/5346d367f72b3a6fba701eb4ea250cbf881d2545/src/models/User.ts#L51) in the [`context` provider](https://github.com/UserOfficeProject/user-office-backend/blob/5346d367f72b3a6fba701eb4ea250cbf881d2545/src/middlewares/graphql.ts#L74)?

**Comment by TickleThePanda** [comment]
The line I've linked to in the `context` is wrong as I think that's for API access tokens. The one I mean is [`line 81`](https://github.com/UserOfficeProject/user-office-backend/blob/5346d367f72b3a6fba701eb4ea250cbf881d2545/src/middlewares/graphql.ts#L81)

**Comment by TCMeldrum** [comment]
Cool I'll give that a go, my idea was to add another GraphQL when `AuthorizedGraphQLClient` in the [request method](https://github.com/UserOfficeProject/user-office-frontend/blob/acaec56d3de65cb01f2b797bf85408cf72919d82/src/hooks/common/useDataApi.ts#L83-L99) but this would be less calls the backend

**Comment by TickleThePanda** [comment]
I think the way that you suggest would mean that we would still allow the API calls with an expired token (if an attacker stole a token from somebody, for example) whereas adding it to `Authorized` makes sure we never miss that where we require a token.
