### ISSUE TITLE
When deploying a new image to prod the old frontend was cached

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/stfc-user-office-project#228]
When a new version is published users may have the frontend resources/pages cached meaning the old version of the frontend will be seen. This was found when I released the front end for the first time as I have the prod frontend cached. As well as causing errors this behavior is very bad and should be fixed.

**Comment by TCMeldrum** [comment]
Frontend was cached for me on release 11-11-2021

**Comment by WhittyPM** [comment]
@TickleThePanda do we need to get this assigned and moved into to do? We are going to have to release again no later than early Friday to see if these problems still exist to give us confidence for Nov 22nd...

**Comment by TickleThePanda** [comment]
@TCMeldrum. Do you know how this went in the last release?

**Comment by TCMeldrum** [comment]
I think it was still a problem (that I noticed it at least I don't know if anyone else noticed anything) in the last release, I noticed an icon that I had removed was still there. F5 did not seem to retrieve the latest changes but ctrl f5 did fetch the latest changes.

**Comment by WhittyPM** [comment]
@TCMeldrum  would this of been the reason we had issues with the instrument scientist functionality?

**Comment by TCMeldrum** [comment]
No, I am that is something separate there is an open issue here:  https://github.com/UserOfficeProject/stfc-user-office-project/issues/278 there is an improperly implemented query causing the problem

**Comment by WhittyPM** [comment]
@TCMeldrum thanks for clarifying. I wondering what the impact will be if we release on Friday?

**Comment by TCMeldrum** [comment]
Any users that have been on the site before might be presented with an old version of the frontend (although this will be hard to tell and I do not know how long the cache lasts), this may mean some features will brake and the features we added may not be visible. If we also need to hotfix the hotfix may also not be visible to anyone who has used the site before the hotfix is released. A simple ctrl + f5 will fix it for any user but it is a far from an ideal solution.

**Comment by WhittyPM** [comment]
@TCMeldrum thank you for explaining. I believe that is does need a fix. We don't want users having to do ctrl+f5. That won't look professional at all and leaves too much room for key features not available to the user. Also too many unknown behaviours...My opinion...

**Comment by TickleThePanda** [comment]
I've had a look into this, I think we're overly caching because we're not setting the `Cache-Control` header. This means the browser will automatically use the latest version of resource. We are setting a `Last-Modified` and `Etag` headers.

The resources we're sharing are unversioned URLs. That means that if we make a change to a resource, we don't change the URL.

We could add the header `Cache-Control: max-age=0, must-revalidate, public` on the proxy which means "please cache this content, and then do not trust your cache". That means that it will cache the large resources but check with the server if they have changed. This means the user won't be hit by the browser redownloading any larger assets but will make sure when they reload the site that the browser is checking if they need to.

However, for anything on the `graphql` endpoint, we should specify `Cache-Control: private` to ensure no caching happens here.

**Comment by mr-field** [comment]
I'd have liked to do this though the Ingress, but we can't. The only way to set extra headers with Nginx is to add [configuration snippets](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#configuration-snippet), which we disabled for https://github.com/isisbusapps/docker-orchestration/issues/177. So it looks like the reverse proxies are the best place for setting the cache control headers.

**Comment by TickleThePanda** [comment]
From my comments in teams.

> **Reverse proxies.** Likely easiest to configure. Very decoupled from the deployments/releases.
> 
> **Ingress.** Not sure how easy this is to configure. Somewhat decoupled from the code/deployments.
> 
> **Frontend/backend.** Bakes the configuration into the nginx image and the backend code. More closely coupled with the code (though the nginx image might not be so clear).
> 
> I think decoupling it has the advantage that we don't need to bake the caching strategy into the software (which means that we don't have to agree with the ESS) but the disadvantage that it might not be so clear in the future.
>
> My preferred is in the reverse proxy as this is where the ESS have also configured theirs (though that's with a different team for them).

Between this and Cosimo's comment, I put together isisbusapps/fba-reverse-proxy#127
