### ISSUE TITLE
Remove sensitive and verbose logs

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/stfc-user-office-project#231]
When there are errors in the backend some of the logs can be very verbose and log sensitive information like API keys. This should be changed to be more concise and not to log sensitive information. Once this has been done the prod API key should be regenerated as it was leaked as part of the logs around early September.

**Comment by mr-field** [comment]
This is blocked by not being able to push a new version of the UOWS client generator to NPM, which prevents us from releasing https://github.com/UserOfficeProject/user-office-lib/pull/83.

**Comment by mr-field** [comment]
Reopening as I need to regenerate the API keys

**Comment by mr-field** [comment]
The API keys have been regenerated on both dev and prod.

BisAppSettings for the change: `stfc-user-office-project-231_replace_proposal_api_keys`

**Comment by ACLay** [comment]
Looks good to me 👍

**Comment by TCMeldrum** [comment]
Looks good 👍

**Comment by mr-field** [comment]
The new API key has been deployed to dev, I've scheduled the prod release for 12:00 on 20/01/2022.

**Comment by mr-field** [comment]
The new API key has been deployed to prod and the old dev and prod keys have been regenerated.

**Comment by mr-field** [comment]
The local environment uses the same key as dev, so the local BisAppSettings config needs to be updated.

See BisAppSettings branch: `user-office-project-231_update_local_api_key`

**Comment by TCMeldrum** [comment]
👍

**Comment by IVlaD17** [comment]
👍

**Comment by mr-field** [comment]
I've merged the fix for the local environment into `develop`.
