### ISSUE TITLE
Test compatible browsers

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#235]
Split from #164 

We should test compatible browsers for this site. This should include current major evergreen browsers (excluding Chrome which is already done by automated tests):
 - Firefox
 - Edge
 - Safari
 - Opera

This needs to be communicated to users as part of the call documentation in #59.

**Comment by ACLay** [comment]
Any browserstack project details should be stored centrally, so that any team members related to the project can use it as needed

**Comment by georgeflecknell** [comment]
![image](https://user-images.githubusercontent.com/75302934/141801338-a6bb6e04-2012-4aae-ac6f-ccfea4a35080.png)

All tests are complete and almost all are successes. There is a problem with save and continue in the latest Firefox build. I have raised this in the Proposals and Outcomes channel.

Refer to proposal id: 131457 on dev.

Unable to progress with values of Years: 1 and weeks: 10 in Firefox 94.0.1

**Comment by TickleThePanda** [comment]
Closed by https://github.com/UserOfficeProject/stfc-user-office-project/issues/235#issuecomment-968983400
