### ISSUE TITLE
Test compatible PDF formats

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#237]
Split from #164 

We need to test a range of PDFs. We should generate some of these in our own environment and use historical problematic PDFs.

We should consider:
 - OS used to make PDF
 - Software used to make PDF
 - PDF standards

We should save the PDFs to use as a database for future testing.

**Comment by georgeflecknell** [comment]
Testing completed so far. 
Process: Upload science case / Save proposal / View as User Officer / Download proposal and view.
Permutations:
Window-Acrobat, Windows-Word, Apple-Acrobat


So far all science cases have been legible within the app and within proposal download from the app.

**Comment by georgeflecknell** [comment]
PDF testing is complete and did not turn up any issues. For each case a new proposal was created and a science case test PDF uploaded. Correct retention and formatting was tested by downloading a copy of the proposal using the on-site controls.

Tested:
Prior non working PDFs - 3
Mac produced PDF using science case - 1
PDF converted by Word to  PDF - 1

These PDFs can all be found in the testing library here:
\\isis\shares\BIS\BrowserTestingNPS

**Comment by TickleThePanda** [comment]
I'm happy that covers this.
