### ISSUE TITLE
Developer support staff will be able to assign the "round manager" role to users

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#24]
Authorised administrators will be able to assign the "round manager" role to users to provide specific access control to round managers

Impacted users: Proposal round managers

Project requirement: [proposal-79](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=79)

**Comment by WhittyPM** [comment]
Following LSF meeting. They confirmed they are happy for developers to assign the round manager roles.

**Comment by TickleThePanda** [comment]
This can be done through support.
