### ISSUE TITLE
Fix max upload size

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#240]
We can't upload files to the proposal submission software which are greater than 1MB but the questionnaire says 2MB. Proposals can have lots of images in them so it's reasonable for them to be up to 2MB.

It looks like the Apache default upload size is at most 2MB and the Nginx default (our k8s ingress) is 1MB.

My gut says that Nginx is causing the problem here though I haven't fully tested it.

This shows as *Error occurred* in the frontend and a response with the status code `413`.

**Comment by TeraMike** [comment]
I've now, after *some* testing, got the correct config setting to get the nginx ingress limit up to 2MB.

There is a question of if the limit might need to be higher. I recall seeing or hearing 10MB somewhere? My opinion is that 2MB should be sufficient, and for now at least it might not be worth the effort/time of potentially fighting Apache to change that default. I will put in a PR for 2MB soon regardless.

**Comment by TeraMike** [comment]
I was able to just use the annotations for the 2MB change increase it again to 10MB. If there any other default upload restrictions they aren't working, but I think it's just nginx. Something to keep in mind if any future changes are needed on the same topic.
