### ISSUE TITLE
Set up real LSF calls

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#242]
Using our existing templates, we should set up the real LSF calls.

### Octopus/Ultra Direct Access and Continuation of Programmes
 - Short code: `LSF 2022_1`
 - Call open: 22nd November 2021.
 - Call close: 18th January 2022.
 - Title: Octopus/Ultra Direct and Continuation of Programmes
 - Reference number format: `2223{digits:4}` (for example 22230000)
 - Call template: LSF Direct Access and Ongoing Programmes
 - Description:
    > You can apply for a maximum four weeks of access during six month allocation period
    > through the Direct Access and Continuation of Programmes access. Successful programme
    > access applicants are required to submit a summary of their progress so far and an outline
    > of the experimental programme to be carried out in the new allocation round. 

### Octopus/Ultra New Programme Access
 - Short code: `LSF_Prog 2022_1`
 - Call open: 22nd November 2021.
 - Call close: 18th January 2022.
 - Title: Octopus/Ultra New Programme Access
 - Reference number format: `22{digits:2}` (for example, 2200).
 - Call template: LSF New Programme
 - Description:
    > Programme access can be awarded to UK academics in support of a research grant
    > which has clearly demonstrated the need for a connected series of experiments.
    > Applicants must have discussed their instrument and experimental requirements
    > with the relevant Facility Head prior to submission of their grant.

**Comment by vyshnavi1605** [comment]
I have set up the real LSF Calls. Is it possible to get a quick review on them?

**Comment by vyshnavi1605** [comment]
I have set up the calls, however there seems to be an issue. When setting up a call and the start date is after the current date, after saving and refreshing, the call seems to disappear.  At the moment the calls are set up to start today, but when I change the start date to 22nd November and refresh the calls seem to disappear. 

Where should I go from here?

**Comment by vyshnavi1605** [comment]
I have set up the calls, would it be possible to get a quick review on them?

**Comment by vyshnavi1605** [comment]
Okay thank you!
