### ISSUE TITLE
Proposal submission email not being sent on dev or prod

### ISSUE THREAD

**Issue by vyshnavi1605** [UserOfficeProject/stfc-user-office-project#244]
After submitting a proposal on prod, the email is not being sent to the user who submitted the proposal.

**Comment by simonfernandes** [comment]
These two fixes don't seem to have fully worked. Or they possibly only resolved part of the problem.

- https://github.com/isisbusapps/docker-orchestration/pull/185
- https://github.com/UserOfficeProject/user-office-backend/pull/472

The "template not found" error has gone, but now they're failing to send for an unspecified reason:

![image](https://user-images.githubusercontent.com/14293717/141967644-03d0e6ed-f501-4cc9-8f87-7d49890a7e53.png)
