### ISSUE TITLE
Update page title

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/stfc-user-office-project#246]
Regardless of where I am in the app or the role I'm logged in as, the web page's title always reads "Welcome to the Users' Office".

I can't see this being a meaningful or helpful title for the vast majority of the users of the site, and combined with #197 there's nothing to suggest when you're on a different tab that this one is the one for proposals or ISIS/CLF/STFC business.

![image](https://user-images.githubusercontent.com/2938284/138686110-265b5ef4-3120-4218-93c8-253ce15b5e27.png)

**Comment by AspectVI** [comment]
Thanks to Panda a Path forward Involving REACT routers, has been proposed though further opinion gathering on the matter is needed. After this, the creation of a design and subsequent review of said design would be necessary.

**Comment by AspectVI** [comment]
I will be proposing 2 solutions to this one using React helmets and the other using hooks and routes.
The first one only addresses titles and will use helmets to overwrite the current title for each page, the second will be able to overwrite both the headers and titles but will be harder for me to do and requires greater changes.

**Comment by AspectVI** [comment]
2 solutions have been found. One for routers, one for components. But currently neither work existing code as of right now and need editing for this purpose.

**Comment by AspectVI** [comment]
<Route path='/' title='Home' exact component={} />  can be used for componant based pages

import { useEffect } from 'react';

/** Hook for changing title */
export const useTitle = title => {
  useEffect(() => {
    const oldTitle = document.title;
    title && (document.title = title);
    // following line is optional, but will reset title when component unmounts
    return () => document.title = oldTitle;
  }, [title]);
};

// improvement:
  <Page
    exact
    path="/"
    component={Index}
    title="Index Page"
  />

**Comment by AspectVI** [comment]
And this for component (still trying to understand how this one works but it did)  <Route path='/' title='Home' exact component={} />

**Comment by AspectVI** [comment]
Thanks to TCM changes have been made. Will now proceed to mirroring these changes across all areas they are needed and then Pushing PR.

**Comment by AspectVI** [comment]
Finished task by changing tests so they aren't confused by there bing multiple 'edit' on the page.
