### ISSUE TITLE
Remove outdated windows path from bisappsettings

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/stfc-user-office-project#247]
`ESS/backend-config/local/development.env` still contains an old windows path to the STFC logo. This setting is now provided via our docker-orchestration repo, so should be removed from bisappsettings.

**Comment by AspectVI** [comment]
@ACLay I have removed the pathing for the STFC Logo and pushed the branch as `WindowsPathRemoval#247` to `BISAppSettings`. How Do I create a PR for this as it is a repo you can view from a browser?

**Comment by AspectVI** [comment]
@ACLay So yesterday I made the change for this Issue and pushed it.  Now I am asking how to Create a PR for this when it is on the BISAppSettings repo? I am guessing I still need to create a PR for it somehow.

**Comment by ACLay** [comment]
It's not quite a pull request, but there is a review process written up here: https://github.com/isisbusapps/ISISBusApps/wiki/Managing-the-BISAppSettings-repo#getting-your-feature-branch-reviewed

**Comment by AspectVI** [comment]
Ok, thank you.

**Comment by AspectVI** [comment]
The `BISAppSettings` branch is `WindowsPathRemoval#247` If some one could review it that would be great

**Comment by ACLay** [comment]
👍 Looks good to me

**Comment by AspectVI** [comment]
I have merged `BISAppSettings` branch `WindowsPathRemoval#247` into `develop` now so that should close this Issue

**Comment by ACLay** [comment]
It doesn't look like there's anything that could go wrong, but for future changes, our policy is to get two approvals before merging stuff in.

**Comment by mr-field** [comment]
Looking at the change after the merge, it looks OK to me.

@AspectVI If this is fixed now, could you cose the issue?
