### ISSUE TITLE
Investigate performance of instrument scientist proposals page

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/stfc-user-office-project#254]
The Instrument Scientist role proposals page (pictured) is slow when filtering proposals.

As an example, load the page and change the "Status" dropdown filter to "All" or "Draft".

The very similar proposals page on the User Officer side seems much quicker in comparison.

![image](https://user-images.githubusercontent.com/14293717/139109946-637a1633-1a8c-4f2f-afa3-ec6ad24b4bc0.png)

**Comment by WhittyPM** [comment]
@TickleThePanda is this part of the existing issue we now have following release. I have pushed into to do.

**Comment by TickleThePanda** [comment]
It wasn't but it is worse that it looked before.
