### ISSUE TITLE
The Co- disappears if the submitter goes back to the "New Proposal page"

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#255]
Feedback from several testers - I noticed that if you add co-proposers, save and continue and then go back to it the co-proposers disappear. Equally the co-proposers are not shown in the downloaded version at all

Not sure if we wanted to add this as a new issue or part of the fix issue currently open

**Comment by TickleThePanda** [comment]
This looks it only effects users who have not yet logged into. Likely this is because there is no dummy record for the user.
