### ISSUE TITLE
As a user I may be confused by the arbitrary number provided before a proposal is submitted

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#260]
We could approach this in one of several ways: 

1) Add a note to say "proposal ID is arbitrary before being submitted. ****Once submitted you will be allocated a permanent reference number****" - or something to that effect. 
2) Leave it for now, see if it becomes an issue. UO are aware of it. 

and 

we add to user documentation (although we know not all users will look at the user docs)

**Comment by srconway** [comment]
I don't know if it would help here but in the Visits system we have the concept of a Visit Request ID which is used until they submit, at which point it changes to a Visit ID. That doesn't seem to cause anyone any confusion so there might be some merit in just referring to the arbitrary value as something like a Proposal Request ID or Draft Proposal ID

**Comment by simonfernandes** [comment]
Sonia's suggestion seems like a nice one here. I think we'd be able to make a check that, if the proposal is in a call that has a reference number format (i.e. the proposal ID will change into a reference number on submission), we display the name of it differently. If the ESS want to use reference numbers and don't want to change the name of the ID, we could always just append some text like `(temporary)` or `(pre-submission ID)` to it.

**Comment by TickleThePanda** [comment]
This only needs to be shown if the _Reference number format_ is set so I'm not sure if we need to consult the ESS on it.
