### ISSUE TITLE
Enable security code scanning

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/stfc-user-office-project#263]
Github now offers [free automatic security scans](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) for all public repos. In theory, these could warn us if potentially insecure code was added to the repo before a PR is merged.

We should consider enabling this on our repos.

**Comment by TickleThePanda** [comment]
Let's bring this up this afternoon with the ESS team.

**Comment by TickleThePanda** [comment]
It does look like future applications of this can be added by anybody - it is just managed through the workflows rather than repository settings.

**Comment by TickleThePanda** [comment]
Closed by UserOfficeProject/user-office-frontend#633 and UserOfficeProject/user-office-backend#471

**Comment by mr-field** [comment]
I think this should be done for the [factory](https://github.com/UserOfficeProject/user-office-factory) too. Even though it's not directly user-facing, it would be useful to know about any security improvements.

**Comment by TickleThePanda** [comment]
Added to factory and lib repos.
