### ISSUE TITLE
As a user I should be able to select a UKRI funding option from the existing drop down list

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#265]
This will require further discussion with Philip/Cristina. This has been requested by Paul (fellow) in CLF but the exact wording needs to be identified to avoid confusion. This may result in being scrapped as there is another option "other". 
Not priority for LSF but is a quick fix if required for ISIS rapid or/and beyond. 

Discuss at board meeting

**Comment by TickleThePanda** [comment]
This wasn't required.
