### ISSUE TITLE
As a user I will be able to click a link in the proposal software that will take me to submitter documentation on CLF SI site

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#271]
Last minute if all set up

**Comment by WhittyPM** [comment]
@TickleThePanda i think this is low priority but if we get time. Even if its after the call

**Comment by TickleThePanda** [comment]
We don't have the documentation on the website right now so we need to wait until that.

**Comment by TickleThePanda** [comment]
Added a link to the documentation to the CLF website on the help page.
