### ISSUE TITLE
Prod file upload size restrictions do not match

### ISSUE THREAD

**Issue by TeraMike** [UserOfficeProject/stfc-user-office-project#280]
You can currently upload more than 10MB ([as a system-wide limit](https://github.com/UserOfficeProject/stfc-user-office-project/issues/240)) while the text on prod explicitly states that the maximum is 2MB.

![image](https://user-images.githubusercontent.com/57662035/141764500-9b5c7834-a319-490a-aebb-3aa8ca0faef9.png)

Here are the main points:
- How likely users are to upload beyond the stated limit is up for debate.  
- This has the upside of allowing documents with detailed figures that may go over the limit slightly to still be accepted.  
- I get the impression that the stated lower restriction is deliberate to save reviewers parsing through massive documents; since the list of restrictions is pretty in-depth, users should follow the guidelines.  
- We do want the capacity for larger files even if not for these initial calls.

We determined at stand-up this was worth making an issue for, even though it may well just be for internal documentation if this is intentional and/or desired behaviour.

**Comment by TickleThePanda** [comment]
I've updated these to say 10MB instead of 2MB now.
