### ISSUE TITLE
As a submitter it would be helpful for me to understand what "constraints" means when I navigate between pages

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#282]
Andy W felt that the message that is currently displayed when trying to navigate pages (and the user has not filled in all mandatory fields) should be the following: 

"Please complete questions marked with a *"

**Not urgent for release**

**Comment by WhittyPM** [comment]
@TickleThePanda added this one from Andys UAT. I can see what he is saying but not high priority

**Comment by TickleThePanda** [comment]
@WhittyPM. I've just tested this and it looks like this shows the constraints are clarified on pages. If any user comes across this again, it should be treated like a bug and we need enough information to clarify it.
