### ISSUE TITLE
Email CSS isn't picked up on dev/prod

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/stfc-user-office-project#286]
In `C:\FBS\Apps\ESS\emails\proposal-submitted\html.pug`, there is a reference to a CSS file. 

Currently this refers to a location at `C:\Programming` which obviously doesn't exist, but changing it to a relative (`styles.css`) or absolute path (`/config/emails/proposal-submitted/styles.css`) also doesn't seem to work.

This only affects the size of the image in the email.

![image](https://user-images.githubusercontent.com/14293717/142174674-2eb0c032-eb0c-4eb3-b98d-ac0dfb3f0861.png)

**Comment by sc19ew** [comment]
Cannot replicate error locally/on dev/on prod

**Comment by sc19ew** [comment]
Issue cannot be replicated on either dev/prod
