### ISSUE TITLE
UOWS may be called hundreds of times per GraphQL request

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/stfc-user-office-project#295]
Authorize header can trigger multiple times on the same graphQL request so we query the UOWS multiple times for the same information like if the token is valid and for a user's role. We should cache these requests within the same graphQL request to speed up performace. This also might be a problem elsewhere but this was the example that I came across.

**Comment by mr-field** [comment]
This is now a priority, as it's preventing users with many proposals from logging in.

**Comment by TickleThePanda** [comment]
Lots of conversation [in teams](https://teams.microsoft.com/l/message/19:f0afa005ea5b474e83109a55c93c16f2@thread.skype/1641997527003?tenantId=3f66361c-a87e-4158-8f61-99e82db3cac8&groupId=403a668a-985f-445b-a4e3-b3a3070bb25b&parentMessageId=1641997527003&teamName=ISIS%20Computing%20Division%20Staff&channelName=Proposals%20and%20Outcomes&createdTime=1641997527003).
