### ISSUE TITLE
Explore the LSF FAP processes with the LSF FAP Secretary, Support, and User Office

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#297]
To do:
 - [x] Initial meeting
 - [x] Investigate data required by access tool
 - [x] Investigate how the LSF FAP secretaries get data to generate their spreadsheets

To help with:
 - https://github.com/UserOfficeProject/stfc-user-office-project/issues/166
 - https://github.com/UserOfficeProject/stfc-user-office-project/issues/168

What we need to do is understand the processes around the FAPs for LSF:
 - What deliverables are needed as part of the FAPs:
    - Expecting FAP booklets, FAP letters, spreadsheets for data collection, FAP management
    - What information
    - What format
 - Find out what tools are used and who uses them
    - Our managed access tools
    - Spreadsheets
    - SharePoint lists
    - Reporting tool
    - Any other software (PDF tools, etc)
 - How and when is everything communicated within the processes

Consider options:
 - Modify existing tools to work with the FAP processes
   - Understand what data is needed to be in various sources:
      - What data is needed in SharePoint
      - What changes do we need to the reporting tool
 - Explore whether new proposal functionality would work for LSF FAP management

**Comment by EdwardHaynes** [comment]
**Summary from the meeting with key LSF and UO members**
The FAP Process is as follows:

- The proposals are downloaded to SharePoint
- All proposals documents are downloaded by Sarah
- Sarah creates a worksheet in Excel with all the proposals details
- Sarah checks the proposals data for issues and corrects where necessary
- Sarah emails Dave and Mike to assign reviewers
- Sarah emails lab managers for comments for main the spreadsheets
- Sarah downloads past experimental reports kept on STFC OneDrive
- Sarah puts the book together manually with Adobe Pro
- Dave checks the book
- The book goes on OneDrive with the experimental reports, and individual proposals documents (The book is not printed like ISIS)
- A form is created for each fap reviewer with a list of proposals they need to review and the FAP meetings are arranged
- Post-fap they receive the results and comments as spreadsheets and word docs that are compiled into a single spreadsheets
- Sarah sends the spreadsheet to the UO with info for them to update on SharePoint lists
- The UO then creates the results letters using CLF FAP Master

**Additional Notes**
- Letters for new Programme are created manually

**Software used during the process**
- Spreadsheets
- Access
- Adobe Pro
- The reporting tool and the new proposals system for high-level data - Science areas, number of proposals, user satisfaction, new PIs
- Onedrive for file storage

**Comment by EdwardHaynes** [comment]
**Notes on LSF FAP MASTER Access Tool**
The following information comes from database tables:
- A number of views from the ISISUserDB Connections Table - AdressesFull, Addresses_People etc
- A Connection to the ID Sequencing Table - Not sure of the specific use

The following are from SharePoint tables:
All proposals and facility data come from Sharepoint lists. The following lists seem relevant:
- Proposal_List_LSF
- LSF_Rounds
- Facility_Area

**Comment by TickleThePanda** [comment]
@EdwardHaynes. Can we close this now?
