### ISSUE TITLE
LSF New Programme route does not generate results letters

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#300]
Issue for “New Programme route”:  One outcome from this meeting; #297 

1) New Programme access does not generate results letters from existing tooling. Sarah Needham currently uses the template and fills in manually, creates a PDF and sends to UO to send to user (UO address). There is not many new programmes but would reduce the work around. 

There is not many new programmes so the benefit vs effort of this potential change needs to be considered. Will this fit in with the changes we are due to make for LSF FAP milestones?

**Comment by WhittyPM** [comment]
Is this likely to be something as part of the project at all? Or LSF round 2....

**Comment by TickleThePanda** [comment]
Not in scope of this project. I've let Sarah know.
