### ISSUE TITLE
Attach publications through DOI

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#308]
To make it easier for reviewers to access publications.
This was requested my LSF staff

This to be reviewed at Phase 3

[Linked to change log ID 11](https://stfc365.sharepoint.com/:x:/r/sites/ISISProject-1102/_layouts/15/Doc.aspx?sourcedoc=%7B0ED023B5-D0EC-42A9-B37F-D3FA0B563CAA%7D&file=Issue%20register.xlsx&action=default&mobileredirect=true)

**Comment by TickleThePanda** [comment]
I think this is a duplicate of #31
