### ISSUE TITLE
NodeJS Windows images are hosted on an internal registry

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/stfc-user-office-project#43]
NodeJS doesn't provide official Docker images for Windows, so the Windows-based Dockerfiles for both the backend and frontend are based on our own basic port of NodeJS. However, the image for this port (`bisapps-node`) is currently hosted on an internal registry in the STFC network and thus can't be pulled outside the STFC sites or VPN.

It would be best to host the image somewhere more accessible so that developers or CI services can pull the images from anywhere. It may be possible to expose the internal registry to the outside world, or host the image on the Docker Hub.

**Comment by mr-field** [comment]
@TCMeldrum I think this was done as part of https://github.com/UserOfficeProject/stfc-user-office-project/issues/120? If there's nothing else to do, could you close it?

**Comment by TCMeldrum** [comment]
Done as part of https://github.com/UserOfficeProject/stfc-user-office-project/issues/120. Our node images are hosted on dockerhub https://hub.docker.com/repository/docker/dmsc/bisapps-node
