### ISSUE TITLE
Design and implement a way to authorise a user, using the STFC user office web service

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#45]
Refs #6

I think for this one, we should think about how are the roles currently used in the application and what changes we might need to make, to make it work.

This will need a design review.

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
Panda's thoughts on how to approach this:
 - Work out how the authorisation works in the UOP
 - Work out how to use our authorisation as part of this
    - How do we decide which authorisation provider to use
    - How do we abstract the authorisation providers (shared interface?)
    - Where will this happen in the code?

**Comment by simonfernandes** [comment]
Hi @UserOfficeProject/swap, would it be possible to get your thoughts on this? 🙂

My understanding so far is that if we took the approach in https://github.com/UserOfficeProject/stfc-user-office-project/issues/44, we (STFC) would have our own DataSource class, selected via an environment variable, that would implement user operations based on our web service and database. The potentially tricky bit for authorisation would be mapping our roles to the 8 roles in the UOP software, where changes on our side may need to be made. This logic could then be placed in `getUserRoles()`. Does this sound like it might work? At the moment I'm unsure whether we (STFC) would want to infer UOP roles from our web service initially, and then store a new, separate set of roles in our own database.
