### ISSUE TITLE
Design and implement a way to get the details about a user, using the STFC user office web service

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#46]
Refs #6 

We need to think about:
 - how to do this and not break the existing database schema
 - how we modify the existing code so that it goes to the right place to get a user's details
 - how we do this efficiently, avoiding lots of fetching of user data

@bolmsten What was your suggestion for it not breaking the existing database schema?

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
I've not assigned anybody on this part yet as I'd like to see how the others go first. It definitely sounds like the most challenging part.

**Comment by TickleThePanda** [comment]
@simonfernandes - I've marked you as assigned to this as I believe you've done it as part of #45

**Comment by simonfernandes** [comment]
Split into https://github.com/UserOfficeProject/stfc-user-office-project/issues/72 and https://github.com/UserOfficeProject/stfc-user-office-project/issues/73
