### ISSUE TITLE
Integrate STFC auth system with proposals app

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/stfc-user-office-project#48]
Our goal is to let STFC users access the proposals system using our existing authentication system, so that users won't need to create new accounts or go through a second login page just for sending proposals. We also want to pull user data from our existing database, without having to duplicate it in the DB for the proposal system.

Since we'll be using our own user management system, we'd also like to disable the login, signup and other user management pages in the frontend.

## Current situation
When a user tries to connect to the proposals app, the frontend checks the browser's local storage for a JWT token. If no token is found, the user is redirected to the login page, where they can enter their email and password (or proceed to the sign-up page if they don't have an account). When the user clicks "login", their email and password are passed to the backend using the `login` user mutation. The backend then uses the email address to retrieve the user from the DB and compares the password in the DB record with the one supplied by the user. If they match, it generates a new JWT token which encodes the user roles and details (such as name and surname), signing it with the value given in the `secret` environment variable. The token is returned to the frontend, which decodes the roles and user info from the token and stores them in the brower's local storage along with the token itself. It then redirects the user to the dashboard page.

Whenever the frontend need to call the GraphQL API, the token is sent with the request using an `Authorization: Bearer` HTTP header. Before sending the request, the frontend also checks if the token needs to be renewed. At the moment, it's set to request a new token if the old one was issued more than 1 hour previously (note that at the moment this is not based on the token expiry date, which is set to 7 days after creation). When a renewal is needed, the frontend sends the old token to the backend using the `getToken` mutation. The backend verifies the token and, if it's valid, returns a new one encoding the same user details and current role. Note that the list of current roles for the new token is looked up again from the DB rather than being copied over like the rest of the data; I am not sure why this is.

![Internal_auth](https://user-images.githubusercontent.com/10788760/97192279-aaef9900-179f-11eb-88d4-61939f11a415.png)

### Overview
The current STFC Auth system uses a token called "session ID" to authenticate a user session. Unlike the JWT used by the proposal system, the session ID does not encode any user data, it's only used to prove the user's identity.

One way of integrating the two systems would be to automatically "translate" the sessionID into a JWT: when the user clicks on a link in the STFC user dashboard, the sessionID is passed to the proposals system, which verifies it and uses it to obtain the user's details and roles. It can then encode this information in a JWT token and store it in the browser's local storage, like it does now.

### Details
We could add a new environment variable (something like `AUTH_TYPE`) to control which type of authentication should be used:
- `internal` corresponds to the current situation. It enables all current user management pages in the frontend, but disables the new `external-auth` route (see below). If an unauthenticated user tries to access the app, they are redirected to the "Sign In" page
- `external` disables all current user management pages, but enables the new `external-auth` route. If an unauthenticated user tries to access the app, they are redirected to an external  login page (the URL could be set by another new env var: `EXTERNAL_AUTH_LOGIN_URL`)

We'll also need a way to pass the session ID from the STFC system to the proposals app. We could do this using URL parameters, for example `/external-auth/xxxx-xxxx-xxxx`. In the proposals app, we could add a new route in the `App` component which pulls out the session ID from the URL and passes it to the backend using a new GraphQL mutation.

In the backend, the mutation resolver could then use the session ID to call the STFC UserOfficeWebService and get the user's details and roles. We'll probably need to translate STFC roles to proposals roles at this point, as they are slighly different. The data can then be encoded in a new JWT token, which is then signed and returned to the frontend. As an extra step, we'll also need to create a dummy entry in the DB if this is the first time the user logs in, containing only their user number from the STFC system as their user ID. This is required to maintain the current foreign key constraints in the proposals DB.

> Note
> If we wanted to, we could make the backend implmentation more generic to potentially allow other types of external authentication in the future. For example, we could define a new interface called `ExternalAuthProvider`, which exposes functions to retrieve the user details and roles based on a given token. The STFC implementation of the interface would call the UserOfficeWebService, but other implementations would be possible for other services. The provider to use could be specified at runtime using an environment variable called something like `EXTERNAL_AUTH_PROVIDER`

Once a JWT token is returned to the frontend, eveything can proceed pretty much unchanged: the token and decoded data are set in the brower's local storage and renewed using the existing methods. A failed external login (i.e. for invalid session IDs) would instead redirect to the external login page.

![External_auth](https://user-images.githubusercontent.com/10788760/97192272-a9be6c00-179f-11eb-9269-1bd5e4801e36.png)

**Comment by TickleThePanda** [comment]
Closing this as the design review is complete (and marked as duplicate to avoid it being included in stats).
