### ISSUE TITLE
Improve dev environment on Windows

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/stfc-user-office-project#49]
The current Windows Dockerfile is suitable for production, but is not ideal for local development. We should modify it so that the code is mounted from the host into the container and changes automatically trigger a recompile.

Some scripts in the backend and frontend `package.json` also assume that the user is running Linux and will fail on Windows. We should either change them to be cross-platfoem or add separate commands for Windows developers.

**Comment by martin-trajanovski** [comment]
@mr-field I am not sure which of the commands inside `package.json` will fail on Windows because I am using Windows on my development machine and I think everything should work so far. Maybe I haven't used all the commands yet but the most common ones are working for sure.

**Comment by mr-field** [comment]
I'm thinking of the `generate:local` command in the frontend which uses `sed` to replace a placeholder string in a config file with the local URL of the backend. We don't have `sed` on our machines (although it's true that we could get it through Git for Windows if necessary), so I was thinking of adding a Powershell command to do the same thing.

Some of the backend scripts also use the `env` command, particulary `test` which we'll definitely need. As far as I know, that's a Bash command which won't work in CMD.

**Comment by mr-field** [comment]
All relevant PRs have been merged and I've documented the STFC workflow on our wiki.
