### ISSUE TITLE
Proposals should be submitted following the existing reference number formats

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#5]
Proposals should be submitted following the existing reference number formats to provide consistency for users and staff

Impacted users: Supporters, Instrument Scientists, Proposal round managers

Project requirement: [proposal-61](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=61)

**Comment by simonfernandes** [comment]
Currently, when a proposal is first saved, a 6 digit short code is generated and stored as a column in the proposals table. This isn't modified when a proposal moves between statuses.

To solve this issue we could add a nullable column to the call table that holds a reference number prefix (e.g. for STFC's case something like "201"), along with a nullable reference number column in proposals. Each proposal that is associated with a single call can use this prefix to generate a reference number when it is submitted. The other option might be to overwrite the short code on submit, though I'm not sure what this might break, and it might be more preferable on our side to keep a pre-submission number.

**Comment by jekabs-karklins** [comment]
Hi Simon, to better understad the question, may I ask what is/are the usecase/s for the reference number? Why can't  proposal id/shortcode be used instead?

I have 2 suggestions but take them with a grain of salt, as I don't have in-depth knowledge of reference number applications

Accepting the premise that reference number is needed, if I understand you correctly then it would be generated only for submitted proposals. This makes me think that there isn't a need for another column on proposals table, but rather a resolver which will inspect the status of the proposal and the call it is in and generate the reference number on the fly. 

I would also suggest calling the column on the Calls table not "prefix" but similarly as with proposals "shortcode" if that makes sense.

**Comment by simonfernandes** [comment]
Hi Jekabs, thanks for your reply and suggestions.

I should have provided a bit more context, sorry! We use reference numbers as a way of tracking a submitted proposal through its various stages in our systems (e.g. scheduling, arranging an experiment visit, reporting, etc.). The reference number itself gives any non-technical person insight into what type of experiment it is. For example, reference number 21230005 tells us that it is the fifth proposal (0005) from the second round (2) of 2021 (21) for the LSF (3) facility. I think this is something that various people in the experiment process like and don't want to change.

When you suggest a GraphQL resolver (which I have limited knowledge on) but to not add another column, how would this be data be saved? Were you thinking to overwrite the short code, or send the reference number out on submitted event?

**Comment by TickleThePanda** [comment]
I think Simon has this right. One thing that might be missing is that the business reference numbers are also used by other applications to refer to proposals. These may need to query these by that reference number.

> This makes me think that there isn't a need for another column on proposals table, but rather a resolver which will inspect the status of the proposal and the call it is in and generate the reference number on the fly.

I don't mind this, as long as the reference number is immutable after submission. However, if our other applications might need to access this information - maybe a DB column would be better?

**Comment by jekabs-karklins** [comment]
Hi, Simmon,

I would like to start by saying that storing additional information on the ID has undesirable side-effects because occasionally the information presented in ID changes along the way thus presenting a dilemma of either updating ID (that might be referenced elsewhere) or keeping the ID (which now contains misleading information). I don't know if that has even been an actual issue for you?

Generating the reference number on the fly does not guarantee immutability in case the underlying data changes, but then we come back to the dilemma, is it more important that ID does not change or that the ID represents the right information.

**Comment by simonfernandes** [comment]
Do you mean that a proposal's data may change after submission, which would change the data in that row and require the reference number to be regenerated? We couldn't just keep this field even if other data changes? I may not have understood you properly.

It looks like currently you store a single row per proposal and when its data is modified or its state changes, it keeps that same row ID - is that correct? In our existing STFC system we create a new row whenever any data changes.

**Comment by jekabs-karklins** [comment]
Hi Simon,

Yes, we use only one row for the proposal in the `proposals` table. And what I mean is that if the reference number contains a call id and the proposal is moved from one call to another, then the ID also would need to be updated.

In general, I can see that we use the field `short_code` for the same purpose you use reference number. So maybe it makes sense if you simply generate the short_code differently to match the format you want?

**Comment by TickleThePanda** [comment]
So, I think there's a few different things we need to consider:
1. The proposal number shouldn't change in a round (even if others are moved or deleted) but you're right that it could be moved between rounds at which it would be changed.
2. A separate reference for a proposal (possibly short code) would still be useful for future integrations with our other services to refer to unsubmitted proposals. For example, listing all of a user's proposals in a dashboard.
3. The proposals need to follow our existing formats.
4. We would need to query by proposal number.

I can think of two options right now. For both of these, I think we'd need to consider how the transactions and locking works to prevent numbers from being given out twice.

### Option 1

We store the reference in the table as a new piece of data. For this, we'd need extra code when moving between rounds to regenerate the number. We may need to track how many proposals have been submitted so far in a call, depending on how things are deleted.

### Option 2

For each proposal we could store which number it was in the series of submitted proposals. For example, this was the 4th submitted in this call. This way, if other things were moved or deleted, each proposal would keep the same number. It might not be as simple as prefix and suffix because *2010XXX* would be a different length (for example, if we don't left pad the suffix with zeros); I don't know if this would be possible to do in a database which could make the decision for us.

**Comment by simonfernandes** [comment]
How does this reference number format sound? It would be attached to a call/round, and then we'd programmatically create an actual reference number from it.

**192{4}**

Where {4} is the number of digits to use for numbering proposals, e.g. 1920001.

The main requirement here I believe is that this is straightforward for the User Office to understand, and it will only be for us at STFC.

@TickleThePanda 
- If a proposal is, say, 4th in the list of submitted proposals for a call (0004), if it is moved to another call, does its position matter in that new call? Would it just become the latest in that new call?
- If the 4th proposal is deleted, should the next submitted proposal become the 5th?

**Comment by TickleThePanda** [comment]
> 192{4}

I think something like `192{sequence:4}` could be better as it would make it more extensible in the future. @jekabs-karklins do you have any thoughts on this?

> If a proposal is, say, 4th in the list of submitted proposals for a call (0004), if it is moved to another call, does its position matter in that new call? Would it just become the latest in that new call?

It would become the latest in the new call.

> If the 4th proposal is deleted, should the next submitted proposal become the 5th?

The next one should be the 5th. We can consider the deleted proposal as "withdrawn".
