### ISSUE TITLE
Confirmation email should have correct content and style

### ISSUE THREAD

**Issue by Scott-James-Hurley** [UserOfficeProject/stfc-user-office-project#52]
We want to send users of the ESS proposal system an email when they submit a proposal or are included in one. We need to decide what the content of the emails will be and their styling which will involve talking to stakeholders.

**Comment by WhittyPM** [comment]
https://users.facilities.rl.ac.uk/auth/ManageDetails.aspx?section=MailingLists

This can help them manage their details: 
https://users.facilities.rl.ac.uk/auth/ManageDetails.aspx?section=Summary

**Comment by WhittyPM** [comment]
@vyshnavi1605 I understand Panda has sent a snap shot of what adjustments need to be made. Did Panda mention that the words "check" would like to be in bold and under checked and the word "facilities access calls". Also for these reminders to be put above the proposal details, yet directly under the first line where it states " You have been included on a proposal for experimental  time at Octopus and Ultra by Vyshnavi Doddi"

**Comment by vyshnavi1605** [comment]
> @vyshnavi1605 I understand Panda has sent a snap shot of what adjustments need to be made. Did Panda mention that the words "check" would like to be in bold and under checked and the word "facilities access calls". Also for these reminders to be put above the proposal details, yet directly under the first line where it states " You have been included on a proposal for experimental time at Octopus and Ultra by Vyshnavi Doddi"

Thank you for the feedback Zoe, I will make the changes.
