### ISSUE TITLE
Set AUTH_TYPE in the backend

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/stfc-user-office-project#53]
As mentioned in the review of https://github.com/UserOfficeProject/user-office-frontend/pull/139, it would be good to set the `REACT_APP_AUTH_TYPE` environment variable in the backend and let the frontend fetch it at runtime.

**Comment by William-Edwards-STFC** [comment]
- [ ] Add database patches to add feature for external auth.
- [ ] Add environment variable to backend to set it to STFC  or not so it won't affect the ESS.
- [ ] Add a featureid check to where we have the current environment variable is checked.

- Check with Cosimo / ESS whether the URL needs to be fetched from the backend or whether it will stay in the frontend
- [ ] If thats the case move the url 
- [ ] Create mutation and fetch it

**Comment by TickleThePanda** [comment]
See https://github.com/UserOfficeProject/user-office-backend/tree/53-move-auth-variable and https://github.com/UserOfficeProject/user-office-frontend/tree/53-move-auth-variable
