### ISSUE TITLE
Deploy software to our dev environment

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#60]
Deploy the software to a dev environment:
 - [x] using database service's databases (see #91)
 - [x] proxy with certificates
 - [x] CI/CD to control the build and releases
 - [x] ~logging (graylog)~
 - [x] ~link with authentication~

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
We should still be able to move ahead with the Jenkins jobs but it might be worth waiting until the next sprint.

**Comment by simonfernandes** [comment]
Amend the legacy proposal host name to its updated domain (`devproposal.facilities.rl.ac.uk` -> `devlegacyproposal.facilities.rl.ac.uk`. This should fix the 500 error that's currently happening.

BisAppSettings branch name: `UserOfficeProject/stfc-user-office-project#60_add_new_dev_proposal`

**Comment by ACLay** [comment]
BisAppSettings change looks good to me 👍

**Comment by TickleThePanda** [comment]
Won't we need an entry for `devproposal.facilities.rl.ac.uk` as well?

**Comment by ACLay** [comment]
Given that we don't have the entrypoint for the new proposals system set up yet, I was happy to approve it to just have users set to redirect to our legacy system

**Comment by simonfernandes** [comment]
> Won't we need an entry for devproposal.facilities.rl.ac.uk as well?

My understanding was that the valid services list was only for constructed redirects back to a service from auth, which the new proposal system doesn't do currently

**Comment by simonfernandes** [comment]
The BisAppSettings branch has been merged now and the devlegacyproposal 500 error seems to have been fixed with it

**Comment by simonfernandes** [comment]
DI ticket **INC-109345** created to 

- create `devkubernetes.devs.facilities.rl.ac.uk` pointing at 130.246.212.237
- add DMZ exception so that FbaProxExWebDev can connect to 130.246.212.237:443 (linux)
- add DMZ exception so that FbaProxExWebDev can connect to 130.246.157.112:6011 (windows)

**Comment by ACLay** [comment]
Presumably those IP's are for machines we already have? I can't see them anywhere on our server list wiki pages. Can they be added to either [servers](https://github.com/isisbusapps/ISISBusApps/wiki/servers) or [docker-servers](https://github.com/isisbusapps/ISISBusApps/wiki/Docker-servers)

**Comment by TickleThePanda** [comment]
INC-109345 is closed complete now and the dev environment works.

I have updated the wiki to include the ingress for the cluster on [SCD Cloud](https://github.com/isisbusapps/ISISBusApps/wiki/Servers#scd-cloud) but it's not worth adding any of the additional nodes there due to the flexibility that we have.
