### ISSUE TITLE
Reporters must be able to use existing business reports in the reporting software

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#7]
Reporters must be able to use existing business reports in the reporting software to enable cross-application reports about experiments and to ensure that reporting stays simple

Impacted users: Reporter

Project requirement: [proposal-71](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=71)

**Comment by Scott-James-Hurley** [comment]
It seems the two most popular ways of doing this is Oracle's heterogeneous connections and data warehousing. 

Heterogeneous connections:
- Allows data in non-Oracle database to be queried using SQL. Supported in the form of transparent gateways, which are vendor specific, or generic connectivity which uses ODBC or OLEDB to make the connections
- Generic connectivity is typically more limited than that possible when using vendor specific gateways, but it is quick and simple to configure
- Vendor specific gateways cost money, generic connectivity seems preferable
- Queries should be automatically modified to work with Postgres, need to create process for converting queries to work with ESS's different database structure

Data Warehouse:
- Central repository of integrated data from one or more disparate sources
- Time-consuming to make
- Rigid
- Could transform data into long format using staging area, no need to alter queries?
- Could use data marts to separate categories
- Could use three-tiered architecture
- Could also create virtual data warehouse using views
   - Faster, easier to set up
   - Less performant

**Comment by TickleThePanda** [comment]
Split into: https://github.com/UserOfficeProject/stfc-user-office-project/issues/76, https://github.com/UserOfficeProject/stfc-user-office-project/issues/77, and https://github.com/UserOfficeProject/stfc-user-office-project/issues/78

**Comment by TickleThePanda** [comment]
@Scott-James-Hurley Do you mind moving design reviews, etc. to #76 please?
