### ISSUE TITLE
Send emails on dev to Bus Apps Sink instead of actual users

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#71]
We should send emails to the bus apps sink email address.

The ESS already have a "switch" on how to handle emails between dev and prod so we may need to modify this implementation for us.

/overwrite opened 2020-09-04

**Comment by simonfernandes** [comment]
Could I run this by you @mr-field:

I had a chat with Tom and there's currently an email event handler (https://github.com/UserOfficeProject/user-office-backend/blob/develop/src/eventHandlers/email.ts) that sends emails on certain events (user created, proposal submitted, etc.). At the moment it looks like we have email templates for each type of event (`C:\FBS\Apps\ESS\emails\proposal-submitted`), where placeholders in the template can be substituted with data (https://github.com/UserOfficeProject/user-office-backend/blob/develop/src/eventHandlers/email.ts#L112). This gives us some flexibility in the email content, but not in which emails are sent and who they're sent to. I think we ideally want to use our own email event handler here, and have suggested that we should do so as part of this issue.

**Comment by mr-field** [comment]
Long term, I think this requires a design review - ideally with both STFC and ESS people - to decide on the best way to enable/disable emails for specific events and how to choose recipients. We could use a separate handler for each facility, or come up with some DB tables and properties to configure which events result in an email (possible even editable through the GUI).

In the short term, I'd rather keep the current logic and simply replace the recipient with the sink inbox when `NODE_ENV` is set to `development`. We're currently the only ones using the SMTP email handler, so it should be fine to add an `if` statement there where the emails are sent to set the recipient to the sink inbox. To make the solution more general, you could take the dev email addres from an environment variable just in case someone else needs to use a different one.

We can then open a new issue for making event emails configurable and talk about it some more.
