### ISSUE TITLE
Convert organisation of STFC users

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/stfc-user-office-project#73]
When getting details of a STFC user from the UOWS, the organisation and nationality are not "translated" when converting the STFC user to the software's `User` model. The `User` model stores the nationality and organisation as numbers, which are foreign keys for respective database tables.

A complication of this is that nationalities stored in the ESS database are stored as country demonyms, while STFC users have an associated country name.

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
Do we need nationality?

**Comment by RasmiaKulan** [comment]
### **Overview and Suggestions**
### _How do we use nationality_
We **only** store the user's organisation's nationality in the address table and that is what is returned by the UOWS in the `BasicPersonDetails` object.
### _How does the ESS use nationality_
They store it as a user's nationality and they are not currently using it but they might in the future for statistics.
### _Existing Proposal System_
The nationality isn't displayed anywhere and doesn't seem to be used for anything.
### _New Proposal System_
- When logged in as a User Officer:
The only area where nationality is displayed is when a user is edited in the list of people.
![Capture](https://user-images.githubusercontent.com/69144386/109325720-2ba5cb00-784e-11eb-9e63-ec56327f22d0.PNG)
- When logged in as a User:
The only area where the nationality is displayed is when a User's profile is viewed.
![Capture](https://user-images.githubusercontent.com/69144386/109326937-acb19200-784f-11eb-9b55-4223912b238c.PNG)
### _Related Problems_
- The current system enables the User Officer to make changes to the user's details. (Should be view only)
- The current system enables Users to enter their details although we have our own user management system responsible for it. (Should be view only)
### _Possible Solutions_
**Option 1:**
Ignore the nationality as even though it is displayed, we can either hide it or rename it to"Nationality of Organisation".

**Option 2:**
We add the user's organisation's nationality as it could have future uses:
- in adding an experimenter as it might help users distinguish between organisations.
- when deciding if a user is eligible for funding
- might want it for display purposes

### _Opinion_
Considering we are adding the organisation, the nationality wouldn't be a great deal of extra work and may be useful in the future even though it's not essential at the moment.

**Comment by TickleThePanda** [comment]
Thanks for putting this together.

I don't think we need to show the user details page; we haven't done it yet but there's work planned for hiding those pages (https://github.com/UserOfficeProject/stfc-user-office-project/issues/54).

So, with that, I think we should leave the nationality empty or null (I think null would be good option) and then ignore the other issues. It's similar to option 1 but I without changing the user details view. As long as we can link back to the organisation in our user details side of things (which I believe we can do via the user, as long as an organisation is only linked to users in the new system), we should have everything that *option 2* provides us.

**Comment by RasmiaKulan** [comment]
What do you mean by:

>  As long as we can link back to the organisation in our user details side of things (which I believe we can do via the user, as long as an organisation is only linked to users in the new system), we should have everything that option 2 provides us.

**Comment by TickleThePanda** [comment]
So, for our reporting, we need to know the country of the Principal Investigator's origin institute (university/company). The institute is attached to the *person* (PI) in our "user details" databases. We link the *proposal* to the *person*. Does that make sense?

I was wrong about it providing "in adding an experimenter as it might help users distinguish between organisations" and "might want it for display purposes" but, even as it is, it provides the essential "when deciding if a user is eligible for funding" which will be done through the reporting tool.

**Comment by TickleThePanda** [comment]
In any case, we shouldn't actually be adding the "nationality" as we don't store that information.

**Comment by RasmiaKulan** [comment]
Thank you for clearing this.
Does it mean we need to link the organisation in this to the institute in our "user details" database or leave it as null?

**Comment by RasmiaKulan** [comment]
### Current Functionality of user objects
The ESS uses two objects for people information:
1. When a user adds an experimenter to a proposal, the organisation is saved in the `BasicUserDetails` object. This object takes the organisation as a string.
2. When the user views information about themselves or when a user officer views the information of a user, the organisation is saved in the `User` object. This object requires the ID of the organisation.

If I don't make any changes to the current code and leave it as it is, whenever the `User` object is used, it won't have the correct organisation (the organisation will be left as '0' and won't have a proper referencing ID).

### Impact of the changes I made
Every time the person information is fetched from the web service and converted into a  `User` object , the database is updated with the new organisation  name if it doesn't already exist.  
Keeping this in mind, if the organisation is changed/updated in our system it will automatically update the database.

**Comment by TickleThePanda** [comment]
> Every time the person information is fetched from the web service and converted into a User object , the database is updated with the new organisation name if it doesn't already exist.

Do we need to store the organisation name in the ESS database? Could it be a dummy empty value to make it clearer that we're getting the data from the UOWS instead?

**Comment by simonfernandes** [comment]
> Could it be a dummy empty value

Do you mean just accepting that wherever the `User` object is used now and in the future won't have an accurate organisation? 

> to make it clearer that we're getting the data from the UOWS instead?

This bit confused me because although we'd be getting the data from the UOWS, we'd essentially be discarding the organisation wouldn't we?

If we do just go with a single row in the institutions table with an empty name (to satisfy the `User` object's organisation property), it feels like creating that single row should be done in a database patch, rather than in the code. Though we don't yet have a way to run patches per environment.

**Comment by TickleThePanda** [comment]
I think the issue is that I don't really understand why we need to store any of the user's organisation information in the database. To me, we should be able to modify the data sources to get this information from the UOWS and transform it - never fetching it from the database. This is at a conceptual level rather than a practical one.

I don't want to block this with my lack of understanding so, if it's very complex, we could go with the initial store in the DB and then change to a cleaner solution in the future. Maybe a more detailed design review could be helpful, with the team, if we haven't already done one? If a design review happened and it was agreed that this was the best way of doing it, then go ahead.

In terms of why it should be avoided: I think storing it in the database, and especially updating it in the database every time, when we're fetching it from another web service should be avoided as there's performance (writing to the database) and conceptual (to a developer) complexity issues in doing that. I know if I came along to code that was doing that, I'd be quite surprised.

If we do have to put something into the database, I understand that there is a requirement on an organisation in the DB to have certain fields to be filled in. However, I think an empty value would be better than a value from our side to make it clearer that the data isn't stored in the DB. Perhaps the ID twice would be better.

**Comment by simonfernandes** [comment]
Ah okay, I see what you mean now, and I agree that ideally it wouldn't be stored in the database at all.

> we should be able to modify the data sources to get this information from the UOWS and transform it - never fetching it from the database

We do this first part (getting it from the UOWS), it's just transforming it to a User object that is the problem. But for us to avoid storing it in the database at all, we'd have to modify the User object to not use an ID and update it everywhere. That sounds like a large change.

I don't think that would be necessary right now, as the only place we currently care about organisation is when adding an experimenter, and that currently gets the data from a different object that takes the organisation name. So I'd be in favour of just inserting a dummy row to satisfy the constraint.

**Comment by TickleThePanda** [comment]
Sounds good to me.

Once the PR is in, could you or Rasmia open an issue to improve it in the future? It can be brought forward if it does cause issues with performance.
