### ISSUE TITLE
Run the database patches against Database Services infrastructure from Jenkins

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#74]
Create a Jenkins Job that builds a PowerShell script that connects to the Postgres database for Proposal Submission and runs through and executes the UOP DB-Patches in directories and subdirectories.

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
@RasmiaKulan Can you update the description of this, please, with more details?

**Comment by mr-field** [comment]
Closed by isisbusapps/deploy-scripts#12
