### ISSUE TITLE
The software will be compatible with available Windows computing infrastructure

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#8]
The software will be compatible with available Windows computing infrastructure to simplify deployment and enable integration with other software

Impacted users: Developers

Project requirement: [proposal-74](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=74)

**Comment by mr-field** [comment]
Both backend and frontend can now run as Windows containers on the STFC dev machines. We still have some limitations at the moment, such as being unable to run the end-to-end tests locally in a Docker container, but I've opened issues on our internal repos to sort those out. One thing that we may want to do on the UserOffice side is #47, to better match the Linux and Windows environments.
