### ISSUE TITLE
Get Database Services to host Postgres databases for prod

### ISSUE THREAD

**Issue by RasmiaKulan** [UserOfficeProject/stfc-user-office-project#90]
This issue refs https://github.com/UserOfficeProject/stfc-user-office-project/issues/75
It will be used to host the Postgres database on prod.

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
Before we can sensibly do this, we need the support expectations and DR plan.

**Comment by RasmiaKulan** [comment]
### Connection details for prod database

Host name/address: `dbspg01.fds.rl.ac.uk`
Port: `5432`
Database: `proposal_submission`
Username: `proposal_submission`
