### ISSUE TITLE
User Office programme manager change - update submission email

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/stfc-user-office-project#94]
Part of https://github.com/isisbusapps/ISISBusApps/issues/560

The email address used in the submission email needs to be updated so that it references Emma's address instead of Andrew's.

The template is stored in `C:\FBS\Apps\ESS\emails\proposal-submitted\html.pug`.

**Comment by TheCyalex** [comment]
FBS branch: stfc-user-office-project#94_update_submission_email)

**Comment by simonfernandes** [comment]
👍

**Comment by JEThompson97** [comment]
My only thought, and it's super nit-picky, is whether it might be worth making the email all lowercase? (Currently it appears the 'A' in _Andrew_ is uppercase). Just for the sake of maintaining convention.

It's not a necessary change, so feel free to take it or leave it 🙂
Otherwise 👍

**Comment by TheCyalex** [comment]
@JEThompson97 the email should be Emma Gozzard's email (it is already all lowercase)

**Comment by JEThompson97** [comment]
@TheCyalex Ahhh, of course. Apologies, I confused myself 😅
👍 from me

**Comment by TheCyalex** [comment]
This has been merged, closing issue
